#include "ParryCounterAbility.h"
#include "AbilitySystemComponent.h"
#include "Abilities/Tasks/AbilityTask_PlayMontageAndWait.h"
#include "GameFramework/Character.h"

UParryCounterAbility::UParryCounterAbility()
{
	InstancingPolicy = EGameplayAbilityInstancingPolicy::InstancedPerActor;
}

void UParryCounterAbility::ActivateAbility(
	const FGameplayAbilitySpecHandle Handle,
	const FGameplayAbilityActorInfo* ActorInfo,
	const FGameplayAbilityActivationInfo ActivationInfo,
	const FGameplayEventData* TriggerEventData)
{
	if (!CommitAbility(Handle, ActorInfo, ActivationInfo))
	{
		EndAbility(Handle, ActorInfo, ActivationInfo, true, false);
		return;
	}

	ACharacter* Character = Cast<ACharacter>(ActorInfo->AvatarActor.Get());
	if (Character && ParryCounterMontage)
	{
		UAbilityTask_PlayMontageAndWait* PlayMontageTask = UAbilityTask_PlayMontageAndWait::CreatePlayMontageAndWaitProxy(
				this, NAME_None, ParryCounterMontage);
		
		PlayMontageTask->OnCompleted.AddDynamic(this, &UParryCounterAbility::OnMontageFinished);
		PlayMontageTask->OnInterrupted.AddDynamic(this, &UParryCounterAbility::OnMontageFinished);
		PlayMontageTask->OnCancelled.AddDynamic(this, &UParryCounterAbility::OnMontageFinished);
		PlayMontageTask->OnBlendOut.AddDynamic(this, &UParryCounterAbility::OnMontageFinished);
		
		PlayMontageTask->ReadyForActivation();
	}
	else
	{
		EndAbility(Handle, ActorInfo, ActivationInfo, false,false);
	}
}

void UParryCounterAbility::OnMontageFinished()
{
	EndAbility(CurrentSpecHandle, CurrentActorInfo, CurrentActivationInfo, false, false);
}
